blank_issues_enabled: false
contact_links:
  - name: If you want to ask or report something else, you can do it privately
    url: https://discord.com/users/402083911053869056
    about: You can DM me (yungsamd17) on Discord.