name: New Mod
description: There is new mod needing to be added.
labels: [New Mod]

body:
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Checklist
      description:
      options:
        - label: I've searched the [issues and pull requests](https://github.com/yungsamd17/np-carmods/issues?q=) for similar looking reports.
          required: true
        - label: I've checked the [NoPixel Vehicle Mods](https://yungsamd17.github.io/np-carmods/) if the mod is not already there.
          required: true

  - type: input
    id: modname
    validations:
      required: true
    attributes:
      label: Mod Name
      description: |
        Full mod name in question, brand and model name.
      placeholder: |
        Example: "Ubermacht Sentinel SG4"

  - type: input
    id: modlink
    validations:
      required: true
    attributes:
      label: Mod Link
      description: Link to either `gta5-mods.com`, `patreon.com` or `tebex store`. Or any other link that the mod is hosted on.
      placeholder: |
        Example: https://www.gta5-mods.com/vehicles/ubermacht-sentinel-sg4-add-on-liveries
